### ISSUE TITLE
List of stuff to do

### ISSUE THREAD

**Issue by shivenmian** [shivenmian/load-balancer-SA#2]
@maniaxiom @Rupal-IIITD Here's the list of what we're supposed to work on. When you're done, just tick the appropriate boxes.
- [x] Add the sample webapp
- [x] Implement and test Round Robin (make sure code runs + running JMeter)
- [x] Implement and test Least Traffic
- [x] Implement and test IP Hashing
- [x] Implement nginx
- [x] Compile the report
